# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Java app to ACR

on:
 workflow_dispatch:
  
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1- Checkout
        uses: actions/checkout@v2

      - name: Step 2- Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'          
          
      - name: Step 8 - build with maven
        run: mvn -B package --file pom.xml

      - name: step-9 ACR login
        uses: azure/docker-login@v1
        with:
          login-server: rahultestwebapp04acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Step 10 - Docker build and push to ACR
        run: |
          docker build . -t rahultestwebapp04acr.azurecr.io/spring-boot-docker.jar:latest
          docker push rahultestwebapp04acr.azurecr.io/spring-boot-docker.jar:latest
          
      - name: Maven Build and Publish to Azure Artifacts
        run: mvn clean deploy -s settings.xml 



